
language: python

python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

virtualenv:
  system_site_packages: true

install:
  - pip install pysam
  - sudo python setup.py install

script: nosetests tests
